# Generated by Django 3.0.2 on 2020-02-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='duration',
        ),
    ]
